<a href="https://colab.research.google.com/github/Fr4nT1c86/hello-world-flutter/blob/master/matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [26]:
#questão D
A = tf.constant([[1,0,2]])
B = tf.constant([[2],[3],[1]])
resultado = tf.matmul(A,B)
print (tf.Session().run(resultado))

[[4]]


In [29]:
#questão E
A = tf.constant([[1,0],[0,0]])
B = tf.constant([[0,1],[1,0]])
resultado = tf.matmul(A,B)
print (tf.Session().run(resultado))

[[0 1]
 [0 0]]


In [31]:
#questão F
A = tf.constant([[1,2],[3,1],[0,3]])
B = tf.constant([[1,0,1],[2,1,0]])
resultado = tf.matmul(A,B)
print (tf.Session().run(resultado))

[[5 2 1]
 [5 1 3]
 [6 3 0]]


In [0]:
#questão G
A = tf.constant([[0,1],[1,0]])
B = tf.constant([[1,0],[0,0]])
resultado = tf.matmul(A,B)
print (tf.Session().run(resultado))

[[27 23]
 [39 32]]
